### PR TITLE
Big cleanup of the tools

### PR DESCRIPTION
**Pull request by AntonioND**
I don't know if you're really interested in maintaining the tools or if you just want to keep their source code on GitHub. If you're not interested in maintaining the tools we can keep the patches in this repository: https://github.com/WonderfulToolchain/wf-nnpack

This PR fixes a lot of warnings in the tools (not all of them yet!) and cleans the code style so that it's a bit easier to read it. There's also a clang-format config file to help with that.

I've also modified the tools so that you need to provide an input path and output path (so that it's easier to integrate the tools with build systems).

### CODE REVIEW

**Comment by PeterLemon** [comment]
Thanks for all you hard work & making the source code up-to-date, fixing warnings & cleaning up all the source. I merged your changes =D

**Comment by AntonioND** [comment]
No worries! If you're happy to take contributions, I'll keep sending PRs here. The Huffman compressor seems to be buggy (even before my changes) and we should have at least a few tests.

**Comment by PeterLemon** [comment]
Hi I tested the Huffman compressor output extensively with 10,000s frames of animation in my N64/GBA video codecs, could you be more specific of how it is buggy? It follows the spec here: https://problemkaputt.de/gbatek.htm#biosdecompressionfunctions
Maybe you are thinking of this part "Data is written in units of 32bits, if the size of the compressed data is not a multiple of 4, please adjust it as much as possible by padding with 0" Anyway Decompressing the output files of the old tool always yielded correct 1:1 binary decompressed output using GBA/NDS Bios decompression functions, & my hand tuned ARM/MIPS assembly decompressors. I can't remember if I had to pad the output Huffman files myself to units of 32bits, I think I may have for them to work. Anyway thanks again for all your help ;)

**Comment by AntonioND** [comment]
I tested it with the `decompress()` function of libnds, and it crashed with a few different tests (a full 256x192 16-bit bitmap, and some smaller text files). Desmume could decompress them correctly with their high-level decompression emulation routine, but melonDS with the BIOS dumps of my DSi and my DSi itself would crash.

I need to check today with other Huffman compressors (like the one that comes with grit) to rule out libnds as a problem, though. If it works with grit, the problem is the CUE compressor. If not, maybe the problem is somewhere else? We'll see.

**Comment by PeterLemon** [comment]
Ah o.k, yep very strange... I should say I never extensively tested Huffman decompression on the NDS/DSi BIOS, only extensively on the GBA hardware using assembly code to use the built in GBA Huffman BIOS decompression function to decompress them correctly. Then I made my own assembly code in ARM for GBA & Raspberry-Pi/MIPS for N64 & PS1 to decompress them correctly in my tests. So either libnds is buggy, the actual NDS/DSi BIOS Huffman decompression routine is buggy, or maybe there was a changed spec for the NDS/DSi Huffman BIOS decompression. Just clutching at straws here lol! Anyway I wish you luck in getting to the root of this problem, happy coding =D

**Comment by PeterLemon** [comment]
I just checked the https://problemkaputt.de/gbatek.htm#biosdecompressionfunctions spec here & it does seem indeed there was a slight change between GBA & NDS/DSi Huffman UnComp specs: HuffUnCompReadNormal - SWI 13h (GBA)
HuffUnCompReadByCallback - SWI 13h (NDS/DSi) Maybe that can help I hope as the Huffman output of this tool may not be forwards compatible with the newer NDS/DSi way of doing stuff. (Although a quick glance makes it seem that is should be forwards compatible)

**Comment by AntonioND** [comment]
Turns out it's a bug in libnds! Mystery solved.

**Comment by PeterLemon** [comment]
Ah thanks for the update, glad you solved that problem, well done!

**Comment by AntonioND** [comment]
Just for reference if someone is curious about it in the future:

https://github.com/blocksds/libnds/compare/0dcf48cf8f8f1240cac2a7918683f771d70b3995...d77fb29cbaeb12c818c431b0710d44b17b274d08

I noticed that when I checked GBATEK: https://problemkaputt.de/gbatek.htm#biosdecompressionfunctions

This buffer was missing:
```
r2 = user defined callback parameter (passed on to Open function)
      (or, for Huffman: pointer to temp buffer, max 200h bytes needed)
r3 = pointer to callback structure
```

And the 32-bit callback:
```
Callback structure (five 32bit pointers to callback functions)

Open_and_get_32bit (eg. LDR r0,[r0], get header)
Close              (optional, 0=none)
Get_8bit           (eg. LDRB r0,[r0])
Get_16bit          (not used)
Get_32bit          (used by Huffman only)
```

**Pull request merged**
